CREATE TABLE CONTATOS (
    ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(70),
    TELEFONE VARCHAR(13),
    CARGO VARCHAR(20),
    CELULAR VARCHAR(13)
);