CREATE TABLE EMPRESAS_REPRESENTADAS (
    ID BIGINT(20) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    CNPJ CHAR(14) NOT NULL,
    RAZAO_SOCIAL VARCHAR(50) NOT NULL,
    CONTATO_ID BIGINT(20),
    ENDERECO_ID BIGINT(20),
    CONSTRAINT FK_EMPRESAS_REPRESENTADAS_CONTATOS
        FOREIGN KEY (CONTATO_ID)
            REFERENCES CONTATOS (ID)
            ON DELETE CASCADE,
    CONSTRAINT FK_EMPRESAS_REPRESENTADAS_ENDERECOS
        FOREIGN KEY (ENDERECO_ID)
            REFERENCES ENDERECOS (ID)
            ON DELETE CASCADE
);